#!/bin/bash
# Contract tests for hooks/session-knowledge.sh — SessionStart injects additionalContext
# when the knowledge base has entries; silent exit 0 when empty or missing.
source "$(dirname "$0")/../lib.sh"

H=session-knowledge.sh

# Helpers -------------------------------------------------------------------

# Create a fixture docs/solutions dir inside a repo with a given INDEX content
make_kb() {
    local repo="$1" index_content="$2" critical_content="${3:-}"
    mkdir -p "$repo/docs/solutions"
    printf '%s\n' "$index_content" > "$repo/docs/solutions/INDEX.md"
    if [ -n "$critical_content" ]; then
        printf '%s\n' "$critical_content" > "$repo/docs/solutions/critical-patterns.md"
    fi
}

# Minimal populated INDEX with one real entry row
_REAL_INDEX='# Knowledge Base Index
> Auto-generated by /compound — do not edit manually.
> Last updated: 2026-06-11 | 1 total entries

## some-category
| File | Type | Severity | Tags | Applicable When |
|---|---|---|---|---|
| [my-entry](some-category/my-entry.md) | knowledge | standard | foo, bar | Use when doing something |'

# Empty formats ---------------------------------------------------------------

t "bootstrap empty format (placeholder row) → silent exit 0"
repo=$(new_repo $H)
make_kb "$repo" '# Knowledge Base Index
> Auto-generated by /compound — do not edit manually.

## Entries
| File | Type | Severity | Tags | Applicable When |
|---|---|---|---|---|
| _(empty — no solutions recorded yet)_ | | | | |'
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
assert_silent_ok

t "rebuild empty format (0 entries header, no data rows) → silent exit 0"
repo=$(new_repo $H)
make_kb "$repo" '# Knowledge Base Index
> Auto-generated by /compound — do not edit manually.
> Last updated: 2026-06-11 | 0 total entries'
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
assert_silent_ok

t "INDEX.md missing → silent exit 0"
repo=$(new_repo $H)
# No docs/solutions dir at all
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
assert_silent_ok

t "has entries → valid JSON output (jq parseable)"
repo=$(new_repo $H)
make_kb "$repo" "$_REAL_INDEX" "# Critical Patterns

## Entry 1
Some content here."
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if [ "$RC" -ne 0 ]; then
    fail "rc=$RC (want 0) — out: $OUT"
elif [ -z "$OUT" ]; then
    fail "expected JSON output, got empty stdout"
elif ! printf '%s' "$OUT" | jq -e . >/dev/null 2>&1; then
    fail "output is not valid JSON — out: $(echo "$OUT" | head -3)"
else
    pass
fi

t "has entries → additionalContext contains entry name from fixture"
repo=$(new_repo $H)
make_kb "$repo" "$_REAL_INDEX" "# Critical Patterns"
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if echo "$OUT" | grep -q "my-entry"; then pass
else fail "expected 'my-entry' in output — out: $(echo "$OUT" | head -3)"; fi

t "INDEX longer than 30 lines → truncated at threshold (31st line content absent)"
repo=$(new_repo $H)
# Build INDEX where line 31 has a distinctive marker
_long_index='# Knowledge Base Index
> Last updated: 2026-06-11 | 1 total entries

## cat
| File | Type | Severity | Tags | Applicable When |
|---|---|---|---|---|
| [entry-a](cat/entry-a.md) | knowledge | standard | a | When A |
line8
line9
line10
line11
line12
line13
line14
line15
line16
line17
line18
line19
line20
line21
line22
line23
line24
line25
line26
line27
line28
line29
line30
SHOULD_BE_TRUNCATED_LINE_31
line32'
make_kb "$repo" "$_long_index"
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if [ -z "$OUT" ]; then
    fail "expected JSON output but got empty stdout"
elif echo "$OUT" | grep -q "SHOULD_BE_TRUNCATED_LINE_31"; then
    fail "line 31 content leaked past the 30-line cap"
else
    pass
fi

t "critical-patterns.md > 40 lines → only heading lines (non-heading body line beyond cap absent)"
repo=$(new_repo $H)
# Build a critical-patterns.md with >40 lines including a distinctive non-heading body line
_cp_lines="# Critical Patterns
## Entry 1
short body"
# Pad to 42 lines total with a distinctive body line on line 42
for i in $(seq 4 41); do
    _cp_lines="$_cp_lines
padding line $i"
done
_cp_lines="$_cp_lines
BODY_LINE_BEYOND_CAP_42"

make_kb "$repo" "$_REAL_INDEX" "$_cp_lines"
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if [ -z "$OUT" ]; then
    fail "expected JSON output but got empty stdout"
elif echo "$OUT" | grep -q "BODY_LINE_BEYOND_CAP_42"; then
    fail "non-heading body line beyond 40-line cap leaked into output"
elif ! echo "$OUT" | grep -q "Critical Patterns"; then
    fail "expected heading '# Critical Patterns' in output"
else
    pass
fi

finish
